### ISSUE TITLE
google fonts

### ISSUE THREAD

**Issue by everything411** [BITNP/cheesy-shrimp#3]
mkdocs material theme need to request `https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i%7CRoboto+Mono:400,400i,700,700i&display=fallback` and it is banned from mainland China, resulting a very long "loading" time

**Comment by YDX-2147483647** [comment]
https://github.com/justjavac/ReplaceGoogleCDN 也许可以参考。

**Comment by YDX-2147483647** [comment]
[Built-in privacy plugin - Material for MkDocs](https://squidfunk.github.io/mkdocs-material/plugins/privacy/)会把外部资源打包，也许启用了就行？

```html
<script src="https://example.com/script.js"></script>
⏬启用后
<script src="assets/external/example.com/script.js"></script>
```
